GET http://localhost:8080/api/projects/

###
GET http://localhost:8080/api/projects/5


###

POST http://localhost:80/api/projects

{
    "title": "Project 1",
    "description": "Project 1 description",
    "id_user_creator": 1
}

###

PATCH http://localhost:8080/api/projects/3

{
    "description": "Project 16 description updated"
}

###

DELETE http://localhost:8080/api/projects/3

###
PATCH http://localhost:8080/api/projects/upvotes/15

###
GET http://localhost:8080/api/projects/search/w

###
GET http://localhost:8080/api/projects/getCollab/6

