GET http://localhost:8080/api/tags

###

GET http://localhost:8080/api/tags/3

###

POST http://localhost:8080/api/tags
Content-Type: application/json

{
    "tag": "HTML"
}

###

PUT http://localhost:8080/api/tags/4
Content-Type: application/json

{
    "tag": "Html"
}

###

DELETE http://localhost:8080/api/tags/4
