get http://localhost:8080/api/user_links

###

get http://localhost:8080/api/user_links/1
###

post http://localhost:8080/api/user_links

{
    "id_user": "15",
    "link": "https://www.google.com/"
}
###

delete http://localhost:8080/api/user_links/1